In [1]:
api_key = "Q1xLNnoSPwFREbyqrtHLW+CoZht6mE8P7heVdJGC9/e5PObIGVOLuIV6"
private_key = "AQdv8ZuiDfVlDwFgq4iVeqtdx/C4deMEzzTkYD9DI0UKEBttNT0zSAvSJeipGl4xkD1jRzd9EPWuN7PL+sFjIQ=="

In [2]:
import krakenex
from pykrakenapi import KrakenAPI
import requests

api = krakenex.API()
k = KrakenAPI(api)

### Getting Price Data

In [3]:
data = k.get_asset_info()
data.head()

,aclass,altname,decimals,display_decimals,status,collateral_value,margin_rate
1INCH,currency,1INCH,10,5,enabled,NaN,NaN
AAVE,currency,AAVE,10,5,enabled,0.8,0.033
ACA,currency,ACA,10,5,enabled,NaN,NaN
ACH,currency,ACH,10,5,enabled,NaN,NaN
ACT,currency,ACT,5,3,enabled,NaN,0

In [4]:
data1 = requests.get('https://api.kraken.com/0/public/Assets').json()
# data1['result']

{'1INCH': {'aclass': 'currency',
  'altname': '1INCH',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'AAVE': {'aclass': 'currency',
  'altname': 'AAVE',
  'decimals': 10,
  'display_decimals': 5,
  'collateral_value': 0.8,
  'status': 'enabled',
  'margin_rate': '0.033'},
 'ACA': {'aclass': 'currency',
  'altname': 'ACA',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'ACH': {'aclass': 'currency',
  'altname': 'ACH',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'ACT': {'aclass': 'currency',
  'altname': 'ACT',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'ACX': {'aclass': 'currency',
  'altname': 'ACX',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'ADA': {'aclass': 'currency',
  'altname': 'ADA',
  'decimals': 8,
  'display_decimals': 6,
  'collateral_value': 0.925,
  'status': 'enabled',
  'margin_rate': '0.021'},
 'ADA.S': {'aclass': 'currency',
  'altname': 'ADA.S',
  'decimals': 8,
  'display_decimals': 6,
  'status': 'enabled'},
 'ADX': {'aclass': 'currency',
  'altname': 'ADX',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'AED': {'aclass': 'currency',
  'altname': 'AED',
  'decimals': 4,
  'display_decimals': 2,
  'status': 'enabled'},
 'AED.HOLD': {'aclass': 'currency',
  'altname': 'AED.HOLD',
  'decimals': 4,
  'display_decimals': 2,
  'status': 'enabled'},
 'AERO': {'aclass': 'currency',
  'altname': 'AERO',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'AEVO': {'aclass': 'currency',
  'altname': 'AEVO',
  'decimals': 6,
  'display_decimals': 4,
  'status': 'enabled',
  'margin_rate': '0'},
 'AGLD': {'aclass': 'currency',
  'altname': 'AGLD',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'AI16Z': {'aclass': 'currency',
  'altname': 'AI16Z',
  'decimals': 6,
  'display_decimals': 4,
  'status': 'enabled',
  'margin_rate': '0'},
 'AIR': {'aclass': 'currency',
  'altname': 'AIR',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'AIXBT': {'aclass': 'currency',
  'altname': 'AIXBT',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'AKT': {'aclass': 'currency',
  'altname': 'AKT',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'ALCH': {'aclass': 'currency',
  'altname': 'ALCH',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'ALCX': {'aclass': 'currency',
  'altname': 'ALCX',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'ALGO': {'aclass': 'currency',
  'altname': 'ALGO',
  'decimals': 8,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'ALGO.S': {'aclass': 'currency',
  'altname': 'ALGO.S',
  'decimals': 8,
  'display_decimals': 5,
  'status': 'enabled'},
 'ALICE': {'aclass': 'currency',
  'altname': 'ALICE',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'ALPHA': {'aclass': 'currency',
  'altname': 'ALPHA',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled'},
 'ALT': {'aclass': 'currency',
  'altname': 'ALT',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'ANKR': {'aclass': 'currency',
  'altname': 'ANKR',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'ANLOG': {'aclass': 'currency',
  'altname': 'ANLOG',
  'decimals': 3,
  'display_decimals': 1,
  'status': 'enabled',
  'margin_rate': '0'},
 'ANON': {'aclass': 'currency',
  'altname': 'ANON',
  'decimals': 6,
  'display_decimals': 4,
  'status': 'enabled',
  'margin_rate': '0'},
 'APE': {'aclass': 'currency',
  'altname': 'APE',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'APENFT': {'aclass': 'currency',
  'altname': 'APENFT',
  'decimals': 2,
  'display_decimals': 1,
  'status': 'enabled',
  'margin_rate': '0'},
 'API3': {'aclass': 'currency',
  'altname': 'API3',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'APT': {'aclass': 'currency',
  'altname': 'APT',
  'decimals': 6,
  'display_decimals': 4,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'APU': {'aclass': 'currency',
  'altname': 'APU',
  'decimals': 2,
  'display_decimals': 1,
  'status': 'enabled',
  'margin_rate': '0'},
 'AR': {'aclass': 'currency',
  'altname': 'AR',
  'decimals': 7,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0'},
 'ARB': {'aclass': 'currency',
  'altname': 'ARB',
  'decimals': 5,
  'display_decimals': 3,
  'collateral_value': 0.9,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'ARC': {'aclass': 'currency',
  'altname': 'ARC',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'ARKM': {'aclass': 'currency',
  'altname': 'ARKM',
  'decimals': 6,
  'display_decimals': 4,
  'status': 'enabled',
  'margin_rate': '0'},
 'ARPA': {'aclass': 'currency',
  'altname': 'ARPA',
  'decimals': 8,
  'display_decimals': 5,
  'status': 'enabled'},
 'ASTR': {'aclass': 'currency',
  'altname': 'ASTR',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'ATH': {'aclass': 'currency',
  'altname': 'ATH',
  'decimals': 4,
  'display_decimals': 4,
  'status': 'enabled',
  'margin_rate': '0'},
 'ATLAS': {'aclass': 'currency',
  'altname': 'ATLAS',
  'decimals': 8,
  'display_decimals': 5,
  'status': 'enabled'},
 'ATOM': {'aclass': 'currency',
  'altname': 'ATOM',
  'decimals': 8,
  'display_decimals': 6,
  'collateral_value': 0.9,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'ATOM.S': {'aclass': 'currency',
  'altname': 'ATOM.S',
  'decimals': 8,
  'display_decimals': 6,
  'status': 'enabled'},
 'ATOM21.S': {'aclass': 'currency',
  'altname': 'ATOM21.S',
  'decimals': 8,
  'display_decimals': 6,
  'status': 'enabled'},
 'AUCTION': {'aclass': 'currency',
  'altname': 'AUCTION',
  'decimals': 7,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0'},
 'AUD.HOLD': {'aclass': 'currency',
  'altname': 'AUD.HOLD',
  'decimals': 4,
  'display_decimals': 2,
  'status': 'enabled'},
 'AUDIO': {'aclass': 'currency',
  'altname': 'AUDIO',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'AVAAI': {'aclass': 'currency',
  'altname': 'AVAAI',
  'decimals': 4,
  'display_decimals': 2,
  'status': 'enabled',
  'margin_rate': '0'},
 'AVAX': {'aclass': 'currency',
  'altname': 'AVAX',
  'decimals': 10,
  'display_decimals': 5,
  'collateral_value': 0.9,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'AVT': {'aclass': 'currency',
  'altname': 'AVT',
  'decimals': 6,
  'display_decimals': 4,
  'status': 'enabled',
  'margin_rate': '0'},
 'AXS': {'aclass': 'currency',
  'altname': 'AXS',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'B3': {'aclass': 'currency',
  'altname': 'B3',
  'decimals': 3,
  'display_decimals': 1,
  'status': 'enabled',
  'margin_rate': '0'},
 'BABY': {'aclass': 'currency',
  'altname': 'BABY',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'BADGER': {'aclass': 'currency',
  'altname': 'BADGER',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'BAL': {'aclass': 'currency',
  'altname': 'BAL',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'BANANAS31': {'aclass': 'currency',
  'altname': 'BANANAS31',
  'decimals': 3,
  'display_decimals': 1,
  'status': 'enabled',
  'margin_rate': '0'},
 'BAND': {'aclass': 'currency',
  'altname': 'BAND',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'BAT': {'aclass': 'currency',
  'altname': 'BAT',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'BCH': {'aclass': 'currency',
  'altname': 'BCH',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'BEAM': {'aclass': 'currency',
  'altname': 'BEAM',
  'decimals': 4,
  'display_decimals': 2,
  'status': 'enabled'},
 'BERA': {'aclass': 'currency',
  'altname': 'BERA',
  'decimals': 6,
  'display_decimals': 4,
  'status': 'enabled',
  'margin_rate': '0'},
 'BICO': {'aclass': 'currency',
  'altname': 'BICO',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'BIGTIME': {'aclass': 'currency',
  'altname': 'BIGTIME',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'BIO': {'aclass': 'currency',
  'altname': 'BIO',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'BIT': {'aclass': 'currency',
  'altname': 'BIT',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'BLUR': {'aclass': 'currency',
  'altname': 'BLUR',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'BLZ': {'aclass': 'currency',
  'altname': 'BLZ',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled'},
 'BMT': {'aclass': 'currency',
  'altname': 'BMT',
  'decimals': 4,
  'display_decimals': 2,
  'status': 'enabled',
  'margin_rate': '0'},
 'BNB': {'aclass': 'currency',
  'altname': 'BNB',
  'decimals': 8,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0'},
 'BNC': {'aclass': 'currency',
  'altname': 'BNC',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'BNT': {'aclass': 'currency',
  'altname': 'BNT',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'BOBA': {'aclass': 'currency',
  'altname': 'BOBA',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled'},
 'BODEN': {'aclass': 'currency',
  'altname': 'BODEN',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'BOND': {'aclass': 'currency',
  'altname': 'BOND',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'BONK': {'aclass': 'currency',
  'altname': 'BONK',
  'decimals': 2,
  'display_decimals': 0,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'BRICK': {'aclass': 'currency',
  'altname': 'BRICK',
  'decimals': 4,
  'display_decimals': 2,
  'status': 'enabled'},
 'BRL': {'aclass': 'currency',
  'altname': 'BRL',
  'decimals': 4,
  'display_decimals': 2,
  'status': 'enabled'},
 'BSX': {'aclass': 'currency',
  'altname': 'BSX',
  'decimals': 2,
  'display_decimals': 2,
  'status': 'enabled'},
 'BTT': {'aclass': 'currency',
  'altname': 'BTT',
  'decimals': 1,
  'display_decimals': 1,
  'status': 'enabled'},
 'C98': {'aclass': 'currency',
  'altname': 'C98',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled'},
 'CAD.HOLD': {'aclass': 'currency',
  'altname': 'CAD.HOLD',
  'decimals': 4,
  'display_decimals': 2,
  'status': 'enabled'},
 'CAKE': {'aclass': 'currency',
  'altname': 'CAKE',
  'decimals': 6,
  'display_decimals': 4,
  'status': 'enabled',
  'margin_rate': '0'},
 'CELO': {'aclass': 'currency',
  'altname': 'CELO',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'CELR': {'aclass': 'currency',
  'altname': 'CELR',
  'decimals': 4,
  'display_decimals': 2,
  'status': 'enabled'},
 'CFG': {'aclass': 'currency',
  'altname': 'CFG',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'CHEEMS': {'aclass': 'currency',
  'altname': 'CHEEMS',
  'decimals': 2,
  'display_decimals': 1,
  'status': 'enabled',
  'margin_rate': '0'},
 'CHF': {'aclass': 'currency',
  'altname': 'CHF',
  'decimals': 4,
  'display_decimals': 2,
  'collateral_value': 1.0,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'CHF.HOLD': {'aclass': 'currency',
  'altname': 'CHF.HOLD',
  'decimals': 4,
  'display_decimals': 2,
  'status': 'enabled'},
 'CHR': {'aclass': 'currency',
  'altname': 'CHR',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'CHZ': {'aclass': 'currency',
  'altname': 'CHZ',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'CLOUD': {'aclass': 'currency',
  'altname': 'CLOUD',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'CLV': {'aclass': 'currency',
  'altname': 'CLV',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'COMP': {'aclass': 'currency',
  'altname': 'COMP',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'CORN': {'aclass': 'currency',
  'altname': 'CORN',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'COTI': {'aclass': 'currency',
  'altname': 'COTI',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'COW': {'aclass': 'currency',
  'altname': 'COW',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'CPOOL': {'aclass': 'currency',
  'altname': 'CPOOL',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'CQT': {'aclass': 'currency',
  'altname': 'CQT',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'CRO': {'aclass': 'currency',
  'altname': 'CRO',
  'decimals': 4,
  'display_decimals': 2,
  'status': 'enabled',
  'margin_rate': '0'},
 'CRV': {'aclass': 'currency',
  'altname': 'CRV',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0.024'},
 'CSM': {'aclass': 'currency',
  'altname': 'CSM',
  'decimals': 6,
  'display_decimals': 3,
  'status': 'enabled'},
 'CTSI': {'aclass': 'currency',
  'altname': 'CTSI',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'CVC': {'aclass': 'currency',
  'altname': 'CVC',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'CVX': {'aclass': 'currency',
  'altname': 'CVX',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'CXT': {'aclass': 'currency',
  'altname': 'CXT',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'CYBER': {'aclass': 'currency',
  'altname': 'CYBER',
  'decimals': 6,
  'display_decimals': 4,
  'status': 'enabled',
  'margin_rate': '0'},
 'DAI': {'aclass': 'currency',
  'altname': 'DAI',
  'decimals': 10,
  'display_decimals': 5,
  'collateral_value': 0.9,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'DASH': {'aclass': 'currency',
  'altname': 'DASH',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'DBR': {'aclass': 'currency',
  'altname': 'DBR',
  'decimals': 4,
  'display_decimals': 2,
  'status': 'enabled',
  'margin_rate': '0'},
 'DENT': {'aclass': 'currency',
  'altname': 'DENT',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'DOGS': {'aclass': 'currency',
  'altname': 'DOGS',
  'decimals': 3,
  'display_decimals': 1,
  'status': 'enabled',
  'margin_rate': '0'},
 'DOLO': {'aclass': 'currency',
  'altname': 'DOLO',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'DOT': {'aclass': 'currency',
  'altname': 'DOT',
  'decimals': 10,
  'display_decimals': 8,
  'collateral_value': 0.925,
  'status': 'enabled',
  'margin_rate': '0.04'},
 'DOT.P': {'aclass': 'currency',
  'altname': 'DOT.P',
  'decimals': 10,
  'display_decimals': 8,
  'status': 'enabled'},
 'DOT.S': {'aclass': 'currency',
  'altname': 'DOT.S',
  'decimals': 10,
  'display_decimals': 8,
  'status': 'enabled'},
 'DOT28.S': {'aclass': 'currency',
  'altname': 'DOT28.S',
  'decimals': 10,
  'display_decimals': 8,
  'status': 'enabled'},
 'DRIFT': {'aclass': 'currency',
  'altname': 'DRIFT',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'DRV': {'aclass': 'currency',
  'altname': 'DRV',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'DUCK': {'aclass': 'currency',
  'altname': 'DUCK',
  'decimals': 3,
  'display_decimals': 1,
  'status': 'enabled',
  'margin_rate': '0'},
 'DYDX': {'aclass': 'currency',
  'altname': 'DYDX',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'DYM': {'aclass': 'currency',
  'altname': 'DYM',
  'decimals': 6,
  'display_decimals': 4,
  'status': 'enabled'},
 'EDGE': {'aclass': 'currency',
  'altname': 'EDGE',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'EGLD': {'aclass': 'currency',
  'altname': 'EGLD',
  'decimals': 8,
  'display_decimals': 5,
  'status': 'enabled'},
 'EIGEN': {'aclass': 'currency',
  'altname': 'EIGEN',
  'decimals': 6,
  'display_decimals': 4,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'ELX': {'aclass': 'currency',
  'altname': 'ELX',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'ENA': {'aclass': 'currency',
  'altname': 'ENA',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'ENJ': {'aclass': 'currency',
  'altname': 'ENJ',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'ENS': {'aclass': 'currency',
  'altname': 'ENS',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'EOS': {'aclass': 'currency',
  'altname': 'EOS',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'ETH2': {'aclass': 'currency',
  'altname': 'ETH2',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'ETH2.S': {'aclass': 'currency',
  'altname': 'ETH2.S',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'ETHFI': {'aclass': 'currency',
  'altname': 'ETHFI',
  'decimals': 6,
  'display_decimals': 4,
  'status': 'enabled',
  'margin_rate': '0'},
 'ETHW': {'aclass': 'currency',
  'altname': 'ETHW',
  'decimals': 7,
  'display_decimals': 5,
  'status': 'enabled'},
 'EUL': {'aclass': 'currency',
  'altname': 'EUL',
  'decimals': 6,
  'display_decimals': 4,
  'status': 'enabled'},
 'EUR.HOLD': {'aclass': 'currency',
  'altname': 'EUR.HOLD',
  'decimals': 4,
  'display_decimals': 2,
  'status': 'enabled'},
 'EUR.M': {'aclass': 'currency',
  'altname': 'EUR.M',
  'decimals': 4,
  'display_decimals': 4,
  'status': 'enabled'},
 'EUROP': {'aclass': 'currency',
  'altname': 'EUROP',
  'decimals': 8,
  'display_decimals': 4,
  'status': 'enabled',
  'margin_rate': '0'},
 'EURQ': {'aclass': 'currency',
  'altname': 'EURQ',
  'decimals': 8,
  'display_decimals': 4,
  'status': 'enabled',
  'margin_rate': '0'},
 'EURR': {'aclass': 'currency',
  'altname': 'EURR',
  'decimals': 8,
  'display_decimals': 4,
  'status': 'enabled',
  'margin_rate': '0'},
 'EURT': {'aclass': 'currency',
  'altname': 'EURT',
  'decimals': 8,
  'display_decimals': 4,
  'status': 'enabled'},
 'EWT': {'aclass': 'currency',
  'altname': 'EWT',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'FARM': {'aclass': 'currency',
  'altname': 'FARM',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'FARTCOIN': {'aclass': 'currency',
  'altname': 'FARTCOIN',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'FET': {'aclass': 'currency',
  'altname': 'FET',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'FHE': {'aclass': 'currency',
  'altname': 'FHE',
  'decimals': 5,
  'display_decimals': 3,
  'status': 'enabled',
  'margin_rate': '0'},
 'FIDA': {'aclass': 'currency',
  'altname': 'FIDA',
  'decimals': 8,
  'display_decimals': 5,
  'status': 'enabled'},
 'FIL': {'aclass': 'currency',
  'altname': 'FIL',
  'decimals': 10,
  'display_decimals': 6,
  'collateral_value': 0.8,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'FIS': {'aclass': 'currency',
  'altname': 'FIS',
  'decimals': 10,
  'display_decimals': 5,
  'status': 'enabled'},
 'FLOKI': {'aclass': 'currency',
  'altname': 'FLOKI',
  'decimals': 3,
  'display_decimals': 1,
  'status': 'enabled',
  'margin_rate': '0.02'},
 'FLOW': {'aclass': 'currency',
  'altname': 'FLOW',
  'decimals': 10,

### Historical Data

In [5]:
ohlc = k.get_ohlc_data('BTCUSD', interval=1440, ascending = True)
ohlc[0].head()

public call frequency exceeded (seconds=0.402782)
 sleeping for 5 seconds

c:\Python311\Lib\site-packages\pykrakenapi\pykrakenapi.py:603: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  ohlc.index.freq = freq

,time,open,high,low,close,vwap,volume,count
dtime,,,,,,,,
2023-05-12,1683849600,26977.9,27102.1,25827.4,26800.0,26406.4,5673.644185,48031
2023-05-13,1683936000,26800.0,27105.5,26700.6,26786.3,26878.3,1548.701574,23366
2023-05-14,1684022400,26788.4,27194.7,26600.0,26923.0,26924.3,1137.433092,21767
2023-05-15,1684108800,26922.2,27677.0,26727.8,27167.6,27296.2,4189.476051,38130
2023-05-16,1684195200,27166.2,27301.2,26850.1,27036.0,27039.9,2539.670482,31535

In [6]:
import pandas as pd

ohlc[0]['20 SMA'] = ohlc[0]['close'].rolling(20).mean()
ohlc_df = ohlc[0] 
ohlc_df.tail()

,time,open,high,low,close,vwap,volume,count,20 SMA
dtime,,,,,,,,,
2025-04-26,1745625600,94717.2,95189.5,93907.5,94663.5,94444.7,499.110036,22248,85990.515
2025-04-27,1745712000,94663.5,95348.5,93621.5,93817.0,94208.2,532.00913,17412,86724.860
2025-04-28,1745798400,93817.0,95600.0,92900.0,94998.1,94444.4,1257.553009,32846,87660.940
2025-04-29,1745884800,94998.1,95469.2,93809.5,94269.6,94878.4,1566.105482,28586,88246.605
2025-04-30,1745971200,94269.7,95195.0,92970.5,94518.9,94152.0,1042.050228,30353,88994.945

In [7]:
import pandas as pd
import plotly.graph_objects as go


fig = go.Figure(data=[
    go.Candlestick(
        x=ohlc_df.index,
        open=ohlc_df['open'],
        high=ohlc_df['high'],
        low=ohlc_df['low'],
        close=ohlc_df['close']
    ),
    go.Scatter(
        x=ohlc_df.index,
        y=ohlc_df['20 SMA'],
        line=dict(color='purple', width=1),
        name='20 SMA'
    )
])

fig.update_layout(title='BTCUSD Candlestick with 20 SMA')
fig.show()

### Get Order Book Data

In [8]:
book = k.get_order_book('AAVEUSD', count = 20)
print(book[0].head())
print(book[1].head())

                         price  volume        time
dtime
2025-04-30 21:48:08  165.49000  19.307  1746049688
2025-04-30 21:48:08  165.63000  26.024  1746049688
2025-04-30 21:48:07  165.38000  11.821  1746049687
2025-04-30 21:48:07  165.59000  10.826  1746049687
2025-04-30 21:48:07  165.68000  12.094  1746049687
                         price  volume        time
dtime
2025-04-30 21:48:07  165.37000   5.959  1746049687
2025-04-30 21:48:07  165.22000   9.421  1746049687
2025-04-30 21:48:07  165.33000   0.605  1746049687
2025-04-30 21:48:07  165.32000  11.820  1746049687
2025-04-30 21:48:07  165.31000  60.118  1746049687

In [10]:
# Merging bid and ask
df = pd.merge(book[0], book[1], left_index=True, right_index=True)
df = df.rename({"price_x":"Bid Price","volume_x":"Bid Amount", "time_x":"Bid Time",
                "price_y":"Ask Price","volume_y":"Ask Amount", "time_y":"Ask Time"}, axis='columns')
df.head()

,Bid Price,Bid Amount,Bid Time,Ask Price,Ask Amount,Ask Time
dtime,,,,,,
2025-04-30 21:48:07,165.38000,11.821,1746049687,165.37000,5.959,1746049687
2025-04-30 21:48:07,165.38000,11.821,1746049687,165.22000,9.421,1746049687
2025-04-30 21:48:07,165.38000,11.821,1746049687,165.33000,0.605,1746049687
2025-04-30 21:48:07,165.38000,11.821,1746049687,165.32000,11.820,1746049687
2025-04-30 21:48:07,165.38000,11.821,1746049687,165.31000,60.118,1746049687

### Executing Trades

In [ ]:
from time import sleep
import krakenex
from pykrakenapi import KrakenAPI
api = krakenex.API()
kraken = KrakenAPI(api)

api.load_key('KrakenPass.txt')